### ISSUE TITLE
There is no vagrant file

### ISSUE THREAD

**Issue by MirrorGuard** [ekazak48/SmallData#1]
There is no vagrant file here. This repo found 17 days before, and nobody make a vagrant file since that time. Hey, people! - Should I do all this work myself? - Ok. But without your commits it would be a hard task. Anyway, I should warning you both: if you will not commit - you will not be recruited to the Neoflex company, because of your uselessness. And at last, but not least, I give you a handicap as well as I will start to do this work from Tuesday, so you have a chance to be much better employees starting this work right now. Or "go away, to the forest" - like Russian says. Thats enough for me. Thats all.

**Comment by ekazak48** [comment]
Now it is a bug, but we can't have Vagrant configuration file until we have some code to execute

**Comment by MirrorGuard** [comment]
Wait. First of all: our code should be configured with vagrant file, isnt it? 
So this is a little bit recursive: we have no vagrant file, because we haven't code as well, as we have no any code without a common config so called vagrant file. What should be done first: code or vagrant file? In my opinion, as well, as a vagrant file is a kinda CONFIG, it should be implementet first. Just to be a something common for us all. 

On the other hand, you told that code should be the first. Okay. But there is one moment unclear for me (as unclear, as it more fair to say that it is a "dirty moment") : how should we integrate our codebase in future, if it wont have a common config?
